const typographys = {
    displayLarge: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '72px',
      fontStyle: 'italic',
      lineHeight: '64px',
      letterSpacing: '-0.25px',
    },
    displayMedium: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '56px',
      fontStyle: 'italic',
      lineHeight: '62px',
      letterSpacing: '0em',
    },
    displaySmall: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '48px',
      fontStyle: 'italic',
      lineHeight: '54px',
      letterSpacing: '0em',
    },
    headlineLarge: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '38px',
      fontStyle: 'italic',
      lineHeight: '44px',
      letterSpacing: '0em',
    },
    headlineMedium: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '28px',
      fontStyle: 'italic',
      lineHeight: '36px',
      letterSpacing: '0em',
    },
    headLineSmall: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '24px',
      fontStyle: 'italic',
      lineHeight: '32px',
      letterSpacing: '0em',
    },
    titleLarge: {
      fontFamily: 'Poppins',
      fontSize: '22px',
      fontWeight: '700',
      fontStyle: 'italic',
      lineHeight: '28px',
      letterSpacing: '0em',
    },
    titleMedium: {
      fontFamily: 'Poppins',
      fontSize: '16px',
      fontWeight: '700',
      fontStyle: 'italic',
      lineHeight: '24px',
      letterSpacing: '0em',
    },
    titleSmall: {
      fontFamily: 'Poppins',
      fontSize: '14px',
      fontWeight: '700',
      fontStyle: 'italic',
      lineHeight: '20px',
      letterSpacing: '0em',
    },
    bodyHuge: {
      fontFamily: 'Poppins',
      fontSize: '22px',
      fontWeight: '400',
      lineHeight: '32px',
      letterSpacing: '0.5px',
    },
    bodyLarge: {
      fontFamily: 'Poppins',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '24px',
      letterSpacing: '0.5px',
    },
    bodyMedium: {
      fontFamily: 'Poppins',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '16px',
      letterSpacing: '0px',
    },
    labelLarge: {
      fontFamily: 'Druk Wide Bold',
      fontSize: '14px',
      fontStyle: 'italic',
      lineHeight: '20px',
      letterSpacing: '0em',
      fontWeight: 950,
    },
    labelMedium: {
      fontFamily: 'Poppins',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '20px',
      letterSpacing: '0.25px',
    },
    labelSmall: {
      fontFamily: 'Poppins',
      fontSize: '11px',
      fontWeight: '200',
      lineHeight: '16px',
      letterSpacing: '0px',
    },
  };

  export default typographys;